version: "3"

services:
  reverse-proxy:
    build: ./reverse-proxy
    image: reverse-proxy
    ports:
      - 8080:8080
    restart: always

  nuxt:
    build: ./frontend
    depends_on:
      - reverse-proxy
    environment:
      ROOT_URL: "http://localhost:8080"
      BASE_URL: "http://localhost:8080/api"
    image: nuxt
    volumes:
      - ./frontend/utils:/app/utils
      - ./frontend/pages:/app/pages
      - ./frontend/styles:/app/styles
      - ./frontend/layouts:/app/layouts
      - ./frontend/components:/app/components
    restart: always

  cms:
    build: ./backend
    image: cms
    restart: always

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: rootdbpassword
    image: mariadb
    restart: always

  adminer:
    image: adminer
    restart: always
