version: "3"

services:
  reverse-proxy:
    build: ./reverse-proxy
    image: reverse-proxy
    ports:
      - 8080:8080
    restart: always

  nuxt:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - reverse-proxy
    image: nuxt
    volumes:
      - ./frontend/utils:/app/utils
      - ./frontend/pages:/app/pages
      - ./frontend/styles:/app/styles
      - ./frontend/layouts:/app/layouts
      - ./frontend/components:/app/components
      - ./frontend/config:/app/config
    restart: always

  cms:
    build: ./backend
    image: cms
    volumes:
      - ./backend/site/assets:/var/www/html/api/site/assets
    restart: always

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: rootdbpassword
    image: mariadb
    restart: always

  adminer:
    image: adminer
    restart: always
