version: "3"

services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile.dev
    image: reverse-proxy
    depends_on:
      - nuxt
      - cms
      - adminer
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./reverse-proxy/services/pictures:/var/www/html/services/pictures
      - ./reverse-proxy/nginx-dev.conf:/etc/nginx/nginx.conf
      - ./reverse-proxy/google8f85531d1eeeaa63.html:/var/www/html/google8f85531d1eeeaa63.html

  nuxt:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: nuxt
    volumes:
      - ./frontend/utils:/app/utils
      - ./frontend/pages:/app/pages
      - ./frontend/styles:/app/styles
      - ./frontend/layouts:/app/layouts
      - ./frontend/components:/app/components
      - ./frontend/config:/app/config
      - ./frontend/static:/app/static
      - ./frontend/store:/app/store
      - ./frontend/middleware:/app/middleware
      - ./frontend/plugins:/app/plugins
      - ./frontend/nuxt.config.js:/app/nuxt.config.js
    restart: always

  cms:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: cms
    volumes:
      - ./backend/site/assets:/var/www/html/api/site/assets
      - ./backend/site/modules:/var/www/html/api/site/modules
      - ./backend/site/ready.php:/var/www/html/api/site/ready.php
      - ./backend/site/templates:/var/www/html/api/site/templates
      - ./backend/site/config-dev.php:/var/www/html/api/site/config-dev.php
    restart: always

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: rootdbpassword
    image: mariadb
    restart: always

  adminer:
    image: adminer
    restart: always
