version: "3"

services:
  reverse-proxy:
    build: ./reverse-proxy
    image: ghcr.io/ptrrr/pplex-proxy:main
    ports:
      - 80:8080
    restart: always

  nuxt:
    image: ghcr.io/ptrrr/pplex-client:main
    depends_on:
      - reverse-proxy
    environment:
      ROOT_URL: "http://pplex.gavillet-cie.com"
      BASE_URL: "http://pplex.gavillet-cie.com/api"
    restart: always

  cms:
    image: ghcr.io/ptrrr/pplex-api:main
    depends_on:
      - reverse-proxy
    restart: always

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: GiBs9EFRrXyNfMmmQ4T7vH
    depends_on:
      - reverse-proxy
    image: mariadb
    restart: always

  adminer:
    image: adminer
    restart: always
