version: "3.4"

services:
  reverse-proxy:
    depends_on:
      - nuxt
      - cms
      - adminer
      - mysql
    build:
      context: ./reverse-proxy
      network: host
      args:
        - CERTBOT_EMAIL=pietro@gavillet-cie.com
        - DOMAIN_LIST=pplex-beta.gavillet-cie.com
    image: ghcr.io/ptrrr/pplex-proxy:main
    ports:
      - 80:8080
      - 443:443
    restart: always
    volumes:
      - letsencrypt:/etc/letsencrypt

  nuxt:
    image: ghcr.io/ptrrr/pplex-client:main
    restart: always

  cms:
    image: ghcr.io/ptrrr/pplex-api:main
    volumes:
      - ./backend/site/assets:/var/www/html/api/site/assets
    restart: always

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: GiBs9EFRrXyNfMmmQ4T7vH
    image: mariadb
    restart: always

  adminer:
    image: adminer
    restart: always

volumes:
  letsencrypt:
