version: "3.4"

services:
  reverse-proxy:
    depends_on:
      - nuxt
      - cms
      - adminer
      - mysql
    image: ghcr.io/gavillet-cie/pplex-proxy:main
    ports:
      - 80:8080
      - 443:443
    restart: on-failure
    volumes:
      - /etc/ssl:/etc/ssl
      - ./reverse-proxy/services/pictures:/var/www/html/services/pictures
      - ./reverse-proxy/google8f85531d1eeeaa63.html:/var/www/html/google8f85531d1eeeaa63.html

  nuxt:
    image: ghcr.io/gavillet-cie/pplex-client:main
    restart: on-failure

  cms:
    image: ghcr.io/gavillet-cie/pplex-api:main
    volumes:
      - ./backend/site/assets:/var/www/html/api/site/assets
    restart: on-failure

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: GiBs9EFRrXyNfMmmQ4T7vH
    image: mariadb
    restart: on-failure

  adminer:
    image: adminer
    restart: on-failure
