version: "3"

services:
  reverse-proxy:
    build: ./reverse-proxy
    image: reverse-proxy
    ports:
      - 80:8080
    restart: always

  nuxt:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - reverse-proxy
    environment:
      ROOT_URL: "http://pplex.gavillet-cie.com"
      BASE_URL: "http://pplex.gavillet-cie.com/api"
    image: nuxt
    restart: always

  cms:
    build: ./backend
    depends_on:
      - reverse-proxy
    image: cms
    restart: always

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: rootdbpassword
    depends_on:
      - reverse-proxy
    image: mariadb
    restart: always

  adminer:
    image: adminer
    restart: always
