const redirects = [
  ['https://pplex.ch/', 'https://www.valfor.ch/en'],
  ['https://pplex.ch/fr/', 'https://www.valfor.ch/fr'],
  ['https://pplex.ch/about-us/', 'https://www.valfor.ch/en/about'],
  ['https://pplex.ch/fr/about-us/', 'https://www.valfor.ch/fr/notre-etude'],
  ['https://pplex.ch/lawyers/', 'https://www.valfor.ch/en/team'],
  ['https://pplex.ch/fr/lawyers/', 'https://www.valfor.ch/fr/equipe'],
  [
    'https://pplex.ch/fr/lawyers/homayoon-arfazadeh/',
    'https://www.valfor.ch/en/team/homayoon-arfazadeh',
  ],
  [
    'https://pplex.ch/fr/lawyers/homayoon-arfazadeh/',
    'https://www.valfor.ch/fr/equipe/homayoon-arfazadeh',
  ],
  [
    'https://pplex.ch/lawyers/philippe-ciocca/',
    'https://www.valfor.ch/en/team/philippe-ciocca',
  ],
  [
    'https://pplex.ch/fr/lawyers/philippe-ciocca/',
    'https://www.valfor.ch/fr/equipe/philippe-ciocca',
  ],
  [
    'https://pplex.ch/lawyers/amir-djafarrian/',
    'https://www.valfor.ch/en/team/amir-djafarrian',
  ],
  [
    'https://pplex.ch/fr/lawyers/amir-djafarrian/',
    'https://www.valfor.ch/fr/equipe/amir-djafarrian',
  ],
  [
    'https://pplex.ch/lawyers/daniel-gatenby/',
    'https://www.valfor.ch/en/team/daniel-gatenby',
  ],
  [
    'https://pplex.ch/fr/lawyers/daniel-gatenby/',
    'https://www.valfor.ch/fr/equipe/daniel-gatenby',
  ],
  [
    'https://pplex.ch/lawyers/nicolas-de-gotrau/',
    'https://www.valfor.ch/en/team/nicolas-de-gotrau',
  ],
  [
    'https://pplex.ch/fr/lawyers/nicolas-de-gotrau/',
    'https://www.valfor.ch/fr/equipe/nicolas-de-gotrau',
  ],
  [
    'https://pplex.ch/lawyers/mathieu-granges/',
    'https://www.valfor.ch/en/team/mathieu-granges',
  ],
  [
    'https://pplex.ch/fr/lawyers/mathieu-granges/',
    'https://www.valfor.ch/fr/equipe/mathieu-granges',
  ],
  [
    'https://pplex.ch/lawyers/dominique-henchoz/',
    'https://www.valfor.ch/en/team/dominique-henchoz',
  ],
  [
    'https://pplex.ch/fr/lawyers/dominique-henchoz/',
    'https://www.valfor.ch/fr/equipe/dominique-henchoz',
  ],
  [
    'https://pplex.ch/lawyers/marc-joory/',
    'https://www.valfor.ch/en/team/marc-joory',
  ],
  [
    'https://pplex.ch/fr/lawyers/marc-joory/',
    'https://www.valfor.ch/fr/equipe/marc-joory',
  ],
  [
    'https://pplex.ch/lawyers/christophe-kalbermatten/',
    'https://www.valfor.ch/en/team/christophe-kalbermatten',
  ],
  [
    'https://pplex.ch/fr/lawyers/christophe-kalbermatten/',
    'https://www.valfor.ch/fr/equipe/christophe-kalbermatten',
  ],
  [
    'https://pplex.ch/lawyers/philippe-kenel/',
    'https://www.valfor.ch/en/team/philippe-kenel',
  ],
  [
    'https://pplex.ch/fr/lawyers/philippe-kenel/',
    'https://www.valfor.ch/fr/equipe/philippe-kenel',
  ],
  [
    'https://pplex.ch/lawyers/benoi-t-lambercy/',
    'https://www.valfor.ch/en/team/benoit-lambercy',
  ],
  [
    'https://pplex.ch/fr/lawyers/benoi-t-lambercy/',
    'https://www.valfor.ch/fr/equipe/benoit-lambercy',
  ],
  [
    'https://pplex.ch/lawyers/jean-yves-rebord/',
    'https://www.valfor.ch/en/team/jean-yves-rebord',
  ],
  [
    'https://pplex.ch/fr/lawyers/jean-yves-rebord/',
    'https://www.valfor.ch/fr/equipe/jean-yves-rebord',
  ],
  [
    'https://pplex.ch/lawyers/thomas-steinmann/',
    'https://www.valfor.ch/en/team/thomas-steinmann',
  ],
  [
    'https://pplex.ch/fr/lawyers/thomas-steinmann/',
    'https://www.valfor.ch/fr/equipe/thomas-steinmann',
  ],
  [
    'https://pplex.ch/lawyers/sundip-k-bhundia/',
    'https://www.valfor.ch/en/team/sundip-k-bhundia',
  ],
  [
    'https://pplex.ch/fr/lawyers/sundip-k-bhundia/',
    'https://www.valfor.ch/fr/equipe/sundip-k-bhundia',
  ],
  [
    'https://pplex.ch/lawyers/feodora-ah-choon/',
    'https://www.valfor.ch/en/team/feodora-ah-choon',
  ],
  [
    'https://pplex.ch/fr/lawyers/feodora-ah-choon/',
    'https://www.valfor.ch/fr/equipe/feodora-ah-choon',
  ],
  [
    'https://pplex.ch/lawyers/virginie-de-kalbermatten/',
    'https://www.valfor.ch/en/team/virginie-de-kalbermatten',
  ],
  [
    'https://pplex.ch/fr/lawyers/virginie-de-kalbermatten/',
    'https://www.valfor.ch/fr/equipe/virginie-de-kalbermatten',
  ],
  [
    'https://pplex.ch/lawyers/talia-poleski/',
    'https://www.valfor.ch/en/team/talia-poleski',
  ],
  [
    'https://pplex.ch/fr/lawyers/talia-poleski/',
    'https://www.valfor.ch/fr/equipe/talia-poleski',
  ],
  [
    'https://pplex.ch/lawyers/anne-claude-knupfer/',
    'https://www.valfor.ch/en/team/anne-claude-knupfer',
  ],
  [
    'https://pplex.ch/fr/lawyers/anne-claude-knupfer/',
    'https://www.valfor.ch/fr/equipe/anne-claude-knupfer',
  ],
  [
    'https://pplex.ch/lawyers/laurence-malherbe/',
    'https://www.valfor.ch/en/team/laurence-malherbe',
  ],
  [
    'https://pplex.ch/fr/lawyers/laurence-malherbe/',
    'https://www.valfor.ch/fr/equipe/laurence-malherbe',
  ],
  [
    'https://pplex.ch/lawyers/alexandra-sierro/',
    'https://www.valfor.ch/en/team/alexandra-sierro',
  ],
  [
    'https://pplex.ch/fr/lawyers/alexandra-sierro/',
    'https://www.valfor.ch/fr/equipe/alexandra-sierro',
  ],
  [
    'https://pplex.ch/lawyers/ali-dehdashti/',
    'https://www.valfor.ch/en/team/ali-dehdashti',
  ],
  [
    'https://pplex.ch/fr/lawyers/ali-dehdashti/',
    'https://www.valfor.ch/fr/equipe/ali-dehdashti',
  ],
  [
    'https://pplex.ch/lawyers/florian-roguet/',
    'https://www.valfor.ch/en/team/florian-roguet',
  ],
  [
    'https://pplex.ch/fr/lawyers/florian-roguet/',
    'https://www.valfor.ch/fr/equipe/florian-roguet',
  ],
  [
    'https://pplex.ch/lawyers/samuel-herzig/',
    'https://www.valfor.ch/en/team/samuel-herzig',
  ],
  [
    'https://pplex.ch/fr/lawyers/samuel-herzig/',
    'https://www.valfor.ch/en/team/samuel-herzig',
  ],
  [
    'https://pplex.ch/lawyers/leo-jedwab/',
    'https://www.valfor.ch/en/team/leo-jedwab',
  ],
  [
    'https://pplex.ch/fr/lawyers/leo-jedwab/',
    'https://www.valfor.ch/fr/equipe/leo-jedwab',
  ],
  [
    'https://pplex.ch/lawyers/ludovic-loretan/',
    'https://www.valfor.ch/en/team/ludovic-loretan',
  ],
  [
    'https://pplex.ch/fr/lawyers/ludovic-loretan/',
    'https://www.valfor.ch/fr/equipe/ludovic-loretan',
  ],
  [
    'https://pplex.ch/lawyers/charlotte-meyer/',
    'https://www.valfor.ch/en/team/charlotte-meyer',
  ],
  [
    'https://pplex.ch/fr/lawyers/charlotte-meyer/',
    'https://www.valfor.ch/fr/equipe/charlotte-meyer',
  ],
  [
    'https://pplex.ch/lawyers/shauna-canale/',
    'https://www.valfor.ch/en/team/shauna-canale',
  ],
  [
    'https://pplex.ch/fr/lawyers/shauna-canale/',
    'https://www.valfor.ch/fr/equipe/shauna-canale',
  ],
  [
    'https://pplex.ch/lawyers/elliott-duplan/',
    'https://www.valfor.ch/en/team/elliott-duplan',
  ],
  [
    'https://pplex.ch/fr/lawyers/elliott-duplan/',
    'https://www.valfor.ch/fr/equipe/elliott-duplan',
  ],
  [
    'https://pplex.ch/lawyers/adriano-cardillo/',
    'https://www.valfor.ch/en/team/adriano-cardillo',
  ],
  [
    'https://pplex.ch/fr/lawyers/adriano-cardillo/',
    'https://www.valfor.ch/fr/equipe/adriano-cardillo',
  ],
  ['https://pplex.ch/our-practice-areas/', 'https://www.valfor.ch/en'],
  ['https://pplex.ch/fr/our-practice-areas/', 'https://www.valfor.ch/fr'],
  ['https://pplex.ch/our-practice-areas/', 'https://www.valfor.ch/en'],
  ['https://pplex.ch/fr/our-practice-areas/', 'https://www.valfor.ch/fr'],
  [
    'https://pplex.ch/our-practice-areas/litigation/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/litigation/',
    'https://www.valfor.ch/fr',
  ],
  [
    'https://pplex.ch/our-practice-areas/litigation/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/litigation/',
    'https://www.valfor.ch/fr',
  ],
  [
    'https://pplex.ch/our-practice-areas/droit-bancaire-et-financier/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/droit-bancaire-et-financier/',
    'https://www.valfor.ch/fr',
  ],
  [
    'https://pplex.ch/our-practice-areas/droit-bancaire-et-financier/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/droit-bancaire-et-financier/',
    'https://www.valfor.ch/fr',
  ],
  [
    'https://pplex.ch/our-practice-areas/droit-de-societes-fusions-et-acquisitions/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/droit-de-societes-fusions-et-acquisitions/',
    'https://www.valfor.ch/fr',
  ],
  [
    'https://pplex.ch/our-practice-areas/droit-de-societes-fusions-et-acquisitions/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/droit-de-societes-fusions-et-acquisitions/',
    'https://www.valfor.ch/fr',
  ],
  [
    'https://pplex.ch/our-practice-areas/employment-and-immigration/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/employment-and-immigration/',
    'https://www.valfor.ch/fr',
  ],
  [
    'https://pplex.ch/our-practice-areas/employment-and-immigration/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/employment-and-immigration/',
    'https://www.valfor.ch/fr',
  ],
  [
    'https://pplex.ch/our-practice-areas/white-collar-crime/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/white-collar-crime/',
    'https://www.valfor.ch/fr',
  ],
  [
    'https://pplex.ch/our-practice-areas/white-collar-crime/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/white-collar-crime/',
    'https://www.valfor.ch/fr',
  ],
  [
    'https://pplex.ch/our-practice-areas/real-estate-construction/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/real-estate-construction/',
    'https://www.valfor.ch/fr',
  ],
  [
    'https://pplex.ch/our-practice-areas/real-estate-construction/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/real-estate-construction/',
    'https://www.valfor.ch/fr',
  ],
  ['https://pplex.ch/our-practice-areas/tax/', 'https://www.valfor.ch/en'],
  ['https://pplex.ch/fr/our-practice-areas/tax/', 'https://www.valfor.ch/fr'],
  ['https://pplex.ch/our-practice-areas/tax/', 'https://www.valfor.ch/en'],
  ['https://pplex.ch/fr/our-practice-areas/tax/', 'https://www.valfor.ch/fr'],
  [
    'https://pplex.ch/our-practice-areas/start-ups/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/start-ups/',
    'https://www.valfor.ch/fr',
  ],
  [
    'https://pplex.ch/our-practice-areas/family-law-and-adult-and-child-protection-law/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/family-law-and-adult-and-child-protection-law/',
    'https://www.valfor.ch/fr',
  ],
  [
    'https://pplex.ch/our-practice-areas/private-clients/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/private-clients/',
    'https://www.valfor.ch/fr',
  ],
  [
    'https://pplex.ch/our-practice-areas/intellectual-property-and-data-protection/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/intellectual-property-and-data-protection/',
    'https://www.valfor.ch/fr',
  ],
  [
    'https://pplex.ch/our-practice-areas/arbitration/',
    'https://www.valfor.ch/en',
  ],
  [
    'https://pplex.ch/fr/our-practice-areas/arbitration/',
    'https://www.valfor.ch/fr/actualites-perspectives',
  ],
  ['https://pplex.ch/news/', 'https://www.valfor.ch/en/news-insights'],
  [
    'https://pplex.ch/fr/news/',
    'https://www.valfor.ch/fr/actualites-perspectives',
  ],
  ['https://pplex.ch/news/', 'https://www.valfor.ch/en/news-insights'],
  [
    'https://pplex.ch/fr/news/',
    'https://www.valfor.ch/fr/actualites-perspectives',
  ],
  [
    'https://pplex.ch/news/python-conseille-la-ville-de-sierre-la-conference-des-presidents-du-district-et-technoark-sa-dans-lacquisition-du-techno-pole/',
    'https://www.valfor.ch/en/news-insights',
  ],
  [
    'https://pplex.ch/fr/news/python-conseille-la-ville-de-sierre-la-conference-des-presidents-du-district-et-technoark-sa-dans-lacquisition-du-techno-pole/',
    'https://www.valfor.ch/fr/actualites-perspectives',
  ],
  [
    'https://pplex.ch/news/python-conseille-la-ville-de-sierre-la-conference-des-presidents-du-district-et-technoark-sa-dans-lacquisition-du-techno-pole/',
    'https://www.valfor.ch/en/news-insights',
  ],
  [
    'https://pplex.ch/fr/news/python-conseille-la-ville-de-sierre-la-conference-des-presidents-du-district-et-technoark-sa-dans-lacquisition-du-techno-pole/',
    'https://www.valfor.ch/fr/actualites-perspectives',
  ],
  [
    'https://pplex.ch/news/interview-of-christophe-de-kalbermatten-in-pme-magazine/',
    'https://www.valfor.ch/en/news-insights',
  ],
  [
    'https://pplex.ch/fr/news/interview-of-christophe-de-kalbermatten-in-pme-magazine/',
    'https://www.valfor.ch/fr/actualites-perspectives',
  ],
  [
    'https://pplex.ch/news/interview-of-christophe-de-kalbermatten-in-pme-magazine/',
    'https://www.valfor.ch/en/news-insights',
  ],
  [
    'https://pplex.ch/fr/news/interview-of-christophe-de-kalbermatten-in-pme-magazine/',
    'https://www.valfor.ch/fr/actualites-perspectives',
  ],
  [
    'https://pplex.ch/news/interview-of-christophe-de-kalbermatten-in-pme-magazine-1/',
    'https://www.valfor.ch/en/news-insights',
  ],
  [
    'https://pplex.ch/fr/news/interview-of-christophe-de-kalbermatten-in-pme-magazine-1/',
    'https://www.valfor.ch/fr/actualites-perspectives',
  ],
  [
    'https://pplex.ch/news/interview-of-christophe-de-kalbermatten-in-pme-magazine-1/',
    'https://www.valfor.ch/en/news-insights',
  ],
  [
    'https://pplex.ch/fr/news/interview-of-christophe-de-kalbermatten-in-pme-magazine-1/',
    'https://www.valfor.ch/fr/actualites-perspectives',
  ],
  [
    'https://pplex.ch/news/maribaud-prend-une-participation-majoritaire-dans-monyco/',
    'https://www.valfor.ch/en/news-insights',
  ],
  [
    'https://pplex.ch/fr/news/maribaud-prend-une-participation-majoritaire-dans-monyco/',
    'https://www.valfor.ch/fr/actualites-perspectives',
  ],
  [
    'https://pplex.ch/news/maribaud-prend-une-participation-majoritaire-dans-monyco/',
    'https://www.valfor.ch/en/news-insights',
  ],
  [
    'https://pplex.ch/fr/news/maribaud-prend-une-participation-majoritaire-dans-monyco/',
    'https://www.valfor.ch/fr/actualites-perspectives',
  ],
  [
    'https://pplex.ch/news/python-me-christophe-de-kalbermatten-advised-t2i-and-its-shareholders-on-all-legal-aspects-of-the-transaction/',
    'https://www.valfor.ch/en/news-insights',
  ],
  [
    'https://pplex.ch/fr/news/python-me-christophe-de-kalbermatten-advised-t2i-and-its-shareholders-on-all-legal-aspects-of-the-transaction/',
    'https://www.valfor.ch/fr/actualites-perspectives',
  ],
  [
    'https://pplex.ch/news/python-me-christophe-de-kalbermatten-advised-t2i-and-its-shareholders-on-all-legal-aspects-of-the-transaction/',
    'https://www.valfor.ch/en/news-insights',
  ],
  [
    'https://pplex.ch/fr/news/python-me-christophe-de-kalbermatten-advised-t2i-and-its-shareholders-on-all-legal-aspects-of-the-transaction/',
    'https://www.valfor.ch/fr/actualites-perspectives',
  ],
  ['https://pplex.ch/deals-cases/', 'https://www.valfor.ch/en/news-insights'],
  [
    'https://pplex.ch/fr/deals-cases/',
    'https://www.valfor.ch/fr/actualites-perspectives',
  ],
  ['https://pplex.ch/deals-cases/', 'https://www.valfor.ch/en/news-insights'],
  [
    'https://pplex.ch/fr/deals-cases/',
    'https://www.valfor.ch/fr/actualites-perspectives',
  ],
  ['https://pplex.ch/contact/', 'https://www.valfor.ch/en/contact'],
  ['https://pplex.ch/fr/contact/', 'https://www.valfor.ch/fr/contact'],
  ['https://pplex.ch/contact/', 'https://www.valfor.ch/en/contact'],
  ['https://pplex.ch/fr/contact/', 'https://www.valfor.ch/fr/contact'],
  ['https://pplex.ch/contact/geneve/', 'https://www.valfor.ch/en/contact'],
  ['https://pplex.ch/fr/contact/geneve/', 'https://www.valfor.ch/fr/contact'],
  ['https://pplex.ch/contact/geneve/', 'https://www.valfor.ch/en/contact'],
  ['https://pplex.ch/fr/contact/geneve/', 'https://www.valfor.ch/fr/contact'],
  [
    'https://pplex.ch/contact/pully-lausanne/',
    'https://www.valfor.ch/en/contact',
  ],
  [
    'https://pplex.ch/fr/contact/pully-lausanne/',
    'https://www.valfor.ch/fr/contact',
  ],
  [
    'https://pplex.ch/contact/pully-lausanne/',
    'https://www.valfor.ch/en/contact',
  ],
  [
    'https://pplex.ch/fr/contact/pully-lausanne/',
    'https://www.valfor.ch/fr/contact',
  ],
  ['https://pplex.ch/contact/sion/', 'https://www.valfor.ch/en/contact'],
  ['https://pplex.ch/fr/contact/sion/', 'https://www.valfor.ch/fr/contact'],
  ['https://pplex.ch/contact/sion/', 'https://www.valfor.ch/en/contact'],
  ['https://pplex.ch/fr/contact/sion/', 'https://www.valfor.ch/en/contact'],
  ['https://pplex.ch/contact/brussels/', 'https://www.valfor.ch/en/contact'],
  ['https://pplex.ch/fr/contact/brussels/', 'https://www.valfor.ch/fr/contact'],
  ['https://pplex.ch/contact/brussels/', 'https://www.valfor.ch/en/contact'],
  ['https://pplex.ch/fr/contact/brussels/', 'https://www.valfor.ch/fr/contact'],
  ['https://pplex.ch/contact/zug/', 'https://www.valfor.ch/en/contact'],
  [
    'https://pplex.ch/fr/contact/untitled-0220209061802/',
    'https://www.valfor.ch/fr/contact',
  ],
  ['https://pplex.ch/contact/zug/', 'https://www.valfor.ch/en/contact'],
  [
    'https://pplex.ch/fr/contact/untitled-0220209061802/',
    'https://www.valfor.ch/fr/contact',
  ],
  ['https://pplex.ch/careers/', 'https://www.valfor.ch/en/career'],
  ['https://pplex.ch/fr/careers/', 'https://www.valfor.ch/fr/emplois'],
  ['https://pplex.ch/careers/', 'https://www.valfor.ch/en/career'],
  ['https://pplex.ch/fr/careers/', 'https://www.valfor.ch/fr/emplois'],
]

export default function ({ app, ssrContext, route, params, redirect }) {
  try {
    const [, currentTarget] = redirects.find(
      (it) => it[0].replace('https://pplex.ch', '') === route.path
    ) || ['', 'https://www.valfor.ch']
    return redirect(301, currentTarget)
  } catch (error) {
    return redirect(301, 'https://www.valfor.ch')
  }
}
