name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ptrrrr/client
        tags: latest, ${{ github.run_number }}
