name: Release
on:
  push:
    branches: [ main ]

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.ZIP_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Build"
          files: |
            update-client.sh
            update-backend.sh
